### ISSUE TITLE
asking for porting when trying to program using your code 

### ISSUE THREAD

**Issue by jbaker5480** [0x9900/SA818#11]
using PRIM board ran code given but when you try to program the sa818 there is a --port argument that it cant find the port confused any help would be great

**Comment by 0x9900** [comment]
Hi J,

The tool SA818 is a generic tool, that can be run on Linux, Windows or Mac, to program the IC radio. For the PIRIM, installed on a raspberry-pi you can ignore this parameter. The program should be able to find the port name by itself. 

Good luck and 73
-fred-

-- 
Fred C.
***@***.***
https://0x9900.com/
https://www.qrz.com/db/W6BSD
