### ISSUE TITLE
Request: Support setting wide/narrow bandwidth

### ISSUE THREAD

**Issue by longview** [0x9900/SA818#14]
Is it possible to add a command line argument for setting the radio bandwidth along with the frequency?
It looks like the script currently sets the wide bandwidth in all cases.

My testing shows a ~2 dB improvement in sensitivity when the narrow filters are used for narrow band transmissions (12 dB SINAD, 1 kHz/2.2 kHz dev, CCITT filters).
This is on the SA818-S (VHF) FW 1.1

And thanks for making this, it's saved me a ton of time!

**Comment by 0x9900** [comment]
I am sorry for taking so long to add that option. 
You can now specify the bandwidth from the command line using the argument: --bw. 
A 0 will indicate narrow bandwidth, and a 1 for wide bandwidth. 

```
>fred% sa818 radio --help
usage: sa818 radio [-h] [--bw {0,1}] --frequency FREQUENCY
                      [--offset OFFSET] [--squelch SQUELCH]
                      [--ctcss CTCSS | --dcs DCS] [--close-tail CLOSE_TAIL]

optional arguments:
  -h, --help            show this help message and exit
  --bw {0,1}            Bandwidth 0=NARROW (12.5KHz), 1=WIDE (25KHx) [default:
                        WIDE]
  --frequency FREQUENCY
                        Receive frequency
  --offset OFFSET       Offset in MHz, 0 for no offset [default: 0.0]
  --squelch SQUELCH     Squelch value (0 to 8) [default: 4]
  --ctcss CTCSS         CTCSS (PL Tone) 0 for no CTCSS [default: None]
  --dcs DCS             DCS code must me the number followed by [N normal] or
                        [I inverse] [default: None]
  --close-tail CLOSE_TAIL
                        Close CTCSS Tail Tone (yes/no)
```
