### ISSUE TITLE
Request: Support setting CTCSS for RX and CTCSS TX

### ISSUE THREAD

**Issue by ChrisAPRS** [0x9900/SA818#15]
Is it possible to add a command line argument for setting the radio CTCSS_RX and CTCSS_TX  frequency ?
Thank you.

**Comment by 0x9900** [comment]
I'm working on it, you should have this capability in a couple of days.

**Comment by 0x9900** [comment]
Done. If you get the latest version it should work. Let me know if you encounter any problems.

**Comment by cdjlele** [comment]
Is it possible to set the tone only for transmission and not for reception?
