### ISSUE TITLE
Suggestion/feature request

### ISSUE THREAD

**Issue by mytechguyri** [0x9900/SA818#17]
Ever consider using an I2S audio solution so you can feed audio direct to the gpio on the pi instead of the USB method?  See [https://github.com/mytechguyri/i2s_audio_phat.git](url)

Then one other improvement... While i love the SA818 modules... they're a bit under powered... they typically don't put out enough power to drive an amp at all, so using them for APRS, while it works (works with the I2S audio above quite well) its just too low powered... BUT, NiceRF also makes the SA868 module... pin and code compatible with the SA818, but its a 2 watt module (actually 1.5W in real world) but that's enough to drive an amp... so it could make a great little digital modes hat... and i think if you look at the i2s_audio_hat, that's on the pi zero form factor, and there are big chunks of board real estate taken up by audio connectors and a microphone, which wouldn't be necessary in a a PIRIF type application... Use an IPX antenna connector, and I'd bet you could fit the i2s audio and the SA868 on a pi zero form factor board...  solar powered remote APRS digipeater?  piece of cake zero, hat, battery, solar panel in a weather proof enclosure.

I was actually going to design this myself, but pcb design is not my area of expertise... and you've got everything nearly done already with your pirim design... it makes more sense to collaborate to make a better wheel than to re-invent it.

73 
WA1OKB

**Comment by 0x9900** [comment]
You are talking about the PIRIM board. 

That program is independent of the PIRIM board. It is for configuring the SA818. 
As soon as I git my hand on an SA868, I will modify this program to also configure this chip.
