### ISSUE TITLE
The latest version problems with programming

### ISSUE THREAD

**Issue by sp2ong** [0x9900/SA818#19]
Hi,

After upgrade to latest version 0.2.3 has problems, when we try for example set volume level produce error

sa818 --port /dev/ttyUSB0 volume --level 8

SA818 set volume error

similar problem with filters

SA818 set filter error

Version 0.2.2 works OK

**Comment by sp2ong** [comment]
When I set --debug show that version 0.2.3 send wrong syntax command:

SA818: DEBUG: Sending: {self.VOLUME}={opts.level:d}


with v0.2.2 in --debug mode show:

SA818: DEBUG: Sending: AT+DMOSETVOLUME=8

I use python3 v3.9.2 and  install  by command

python3 -m pip install sa818

**Comment by 0x9900** [comment]
Hello, and sorry about the problem.

I committed to a new version that should fix the problem. You can install the new version
using PyPI (https://pypi.org/project/sa818/0.2.4/) or getting the sources directly from GitHub.

If you need any help with anything, please let me know. 
73
-fred-

**Comment by 0x9900** [comment]
New version has been released

**Comment by 0x9900** [comment]
A new version has been published.

**Comment by sp2ong** [comment]
OK thank you very much
