### ISSUE TITLE
CTCSS enable it only for transmission

### ISSUE THREAD

**Issue by cdjlele** [0x9900/SA818#22]
Is it possible to set the tone only for transmission and not for reception?

Thank's

**Comment by 0x9900** [comment]
I'm sorry for not getting back to you sooner. 
Yes, setting a different tone for receiving and transmitting is possible.
You can use the option `--ctcss` followed by 2 numbers separated by a comma. The firest number is for tx the second for transmit.
For example: `--ctcss 94.8,103.5`

**Comment by armel** [comment]
Hello @cdjlele,

I just made a [PR](https://github.com/0x9900/SA818/pull/26) (pull request) for that.

Regards,

Armel F4HWN.

**Comment by 0x9900** [comment]
I have merged your changes. Thank you so much for sending your code.
-fred-

**Comment by armel** [comment]
You're welcome Fred. Thank you, it's been a pleasure 😌
