### ISSUE TITLE
Auto "--port" selection could be improved

### ISSUE THREAD

**Issue by Allan-N** [0x9900/SA818#23]
I have an SA818 that is connected to "/dev/ttyUSB0".  The gotcha is that my system also has both "/dev/serial0" and "/dev/ttyUSB0".  If I do not explicitly specify the "--port PORT" argument then `sa818.py` first tries "/dev/serial0", fails with a "Connection error", and not continue trying "/dev/ttyUSB0".

```
root@node1001:~# sa818 --port /dev/serial0 version
Connection error
root@node1001:~# sa818 --port /dev/ttyUSB0 version
SA818: INFO: Firmware SA818, version: V4.1
```

Note: all is well if I explicitly specify "--port /dev/ttyUSB0".  Needing to specify the argument just defeats the purpose of having the port search list.

**Comment by 0x9900** [comment]
Thank you for sending your code. I have merged it. 
-fred-
